// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJDJ7sut_ZT_XMhanTyFFbUjcmMx985Q',
    appId: '1:649025183049:web:d77ccb4b83fdda0df1ce98',
    messagingSenderId: '649025183049',
    projectId: 'aura-coach-ai',
    authDomain: 'aura-coach-ai.firebaseapp.com',
    storageBucket: 'aura-coach-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMt2a1IuQdbxGB1B9oaFQHjpYlh9GkpMk',
    appId: '1:649025183049:android:8e0fde2831ff21b3f1ce98',
    messagingSenderId: '649025183049',
    projectId: 'aura-coach-ai',
    storageBucket: 'aura-coach-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQSy2gJV32M5ZHFU7cgjilVEpCkqfULd0',
    appId: '1:1010679582317:ios:2250f6d7719ed3f00d7964',
    messagingSenderId: '1010679582317',
    projectId: 'emerald-green-1754237937',
    storageBucket: 'emerald-green-1754237937.firebasestorage.app',
    iosBundleId: 'com.auracoach.auraCoachAi',
    iosClientId:
        '1010679582317-ct690bfhv6edojjcupoc12vmiub9cu30.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQSy2gJV32M5ZHFU7cgjilVEpCkqfULd0',
    appId: '1:1010679582317:ios:2250f6d7719ed3f00d7964',
    messagingSenderId: '1010679582317',
    projectId: 'emerald-green-1754237937',
    storageBucket: 'emerald-green-1754237937.firebasestorage.app',
    iosBundleId: 'com.auracoach.auraCoachAi',
    iosClientId:
        '1010679582317-ct690bfhv6edojjcupoc12vmiub9cu30.apps.googleusercontent.com',
  );
}
