// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kDebugMode, kIsWeb, TargetPlatform, debugPrint;

// ⚠️  P0 PRODUCTION ISSUE — iOS / macOS Firebase project mismatch ⚠️
// =====================================================================
// web + android  →  project "aura-coach-ai"          (canonical)
// ios + macos    →  project "emerald-green-1754237937" (legacy, MUST migrate)
//
// Effect: iOS users sign in to a different Firebase backend. Their
// conversations, library, and sessions DO NOT sync with Android/web
// users on the same email. Auth tokens issued on iOS will fail when
// the backend is later unified.
//
// Fix: docs/setup/api-key-restrictions.md §2 "iOS / macOS Firebase
// project unification". Requires Firebase Console access:
//
//   1. Add iOS app to `aura-coach-ai` project in Firebase Console.
//   2. Download new GoogleService-Info.plist → replace
//      ios/Runner/GoogleService-Info.plist.
//   3. Run `flutterfire configure --project=aura-coach-ai` to regen
//      this file with the correct iOS section.
//   4. Update CFBundleURLSchemes in ios/Runner/Info.plist with the new
//      REVERSED_CLIENT_ID.
//
// Until that happens, the runtime check below logs a loud warning on
// debug builds so we don't accidentally ship the mismatch.
// =====================================================================

const String _canonicalFirebaseProjectId = 'aura-coach-ai';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    final options = _resolve();
    // Loud warning during development if a platform's Firebase project
    // diverges from the canonical one. Release builds skip this check
    // for performance.
    if (kDebugMode && options.projectId != _canonicalFirebaseProjectId) {
      debugPrint(
        '⚠️  [FIREBASE PROJECT MISMATCH] '
        'Platform ${defaultTargetPlatform.name} is using project '
        '"${options.projectId}" but the canonical project is '
        '"$_canonicalFirebaseProjectId". '
        'See docs/setup/api-key-restrictions.md §2.',
      );
    }
    return options;
  }

  static FirebaseOptions _resolve() {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJDJ7sut_ZT_XMhanTyFFbUjcmMx985Q',
    appId: '1:649025183049:web:d77ccb4b83fdda0df1ce98',
    messagingSenderId: '649025183049',
    projectId: 'aura-coach-ai',
    authDomain: 'aura-coach-ai.firebaseapp.com',
    storageBucket: 'aura-coach-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMt2a1IuQdbxGB1B9oaFQHjpYlh9GkpMk',
    appId: '1:649025183049:android:8e0fde2831ff21b3f1ce98',
    messagingSenderId: '649025183049',
    projectId: 'aura-coach-ai',
    storageBucket: 'aura-coach-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWOR6cudVn-pi3fS60ZgP0qo8MNN9CJM',
    appId: '1:649025183049:ios:4ee39c6c095eaa32f1ce98',
    messagingSenderId: '649025183049',
    projectId: 'aura-coach-ai',
    storageBucket: 'aura-coach-ai.firebasestorage.app',
    iosBundleId: 'com.auracoach.auraCoachAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBWOR6cudVn-pi3fS60ZgP0qo8MNN9CJM',
    appId: '1:649025183049:ios:4ee39c6c095eaa32f1ce98',
    messagingSenderId: '649025183049',
    projectId: 'aura-coach-ai',
    storageBucket: 'aura-coach-ai.firebasestorage.app',
    iosBundleId: 'com.auracoach.auraCoachAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcJDJ7sut_ZT_XMhanTyFFbUjcmMx985Q',
    appId: '1:649025183049:web:5c442c15f36308dbf1ce98',
    messagingSenderId: '649025183049',
    projectId: 'aura-coach-ai',
    authDomain: 'aura-coach-ai.firebaseapp.com',
    storageBucket: 'aura-coach-ai.firebasestorage.app',
  );

}